//go:build sweep
// +build sweep

package sweep_test

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"
	_ "github.com/hashicorp/terraform-provider-aws/service/accessanalyzer"
	_ "github.com/hashicorp/terraform-provider-aws/service/acm"
	_ "github.com/hashicorp/terraform-provider-aws/service/acmpca"
	_ "github.com/hashicorp/terraform-provider-aws/service/amplify"
	_ "github.com/hashicorp/terraform-provider-aws/service/apigateway"
	_ "github.com/hashicorp/terraform-provider-aws/service/apigatewayv2"
	_ "github.com/hashicorp/terraform-provider-aws/service/appconfig"
	_ "github.com/hashicorp/terraform-provider-aws/service/appmesh"
	_ "github.com/hashicorp/terraform-provider-aws/service/apprunner"
	_ "github.com/hashicorp/terraform-provider-aws/service/appstream"
	_ "github.com/hashicorp/terraform-provider-aws/service/appsync"
	_ "github.com/hashicorp/terraform-provider-aws/service/autoscaling"
	_ "github.com/hashicorp/terraform-provider-aws/service/autoscalingplans"
	_ "github.com/hashicorp/terraform-provider-aws/service/backup"
	_ "github.com/hashicorp/terraform-provider-aws/service/batch"
	_ "github.com/hashicorp/terraform-provider-aws/service/budgets"
	_ "github.com/hashicorp/terraform-provider-aws/service/cloud9"
	_ "github.com/hashicorp/terraform-provider-aws/service/cloudformation"
	_ "github.com/hashicorp/terraform-provider-aws/service/cloudfront"
	_ "github.com/hashicorp/terraform-provider-aws/service/cloudhsmv2"
	_ "github.com/hashicorp/terraform-provider-aws/service/cloudsearch"
	_ "github.com/hashicorp/terraform-provider-aws/service/cloudtrail"
	_ "github.com/hashicorp/terraform-provider-aws/service/cloudwatch"
	_ "github.com/hashicorp/terraform-provider-aws/service/cloudwatchlogs"
	_ "github.com/hashicorp/terraform-provider-aws/service/codeartifact"
	_ "github.com/hashicorp/terraform-provider-aws/service/codebuild"
	_ "github.com/hashicorp/terraform-provider-aws/service/codedeploy"
	_ "github.com/hashicorp/terraform-provider-aws/service/codepipeline"
	_ "github.com/hashicorp/terraform-provider-aws/service/cognitoidp"
	_ "github.com/hashicorp/terraform-provider-aws/service/configservice"
	_ "github.com/hashicorp/terraform-provider-aws/service/connect"
	_ "github.com/hashicorp/terraform-provider-aws/service/cur"
	_ "github.com/hashicorp/terraform-provider-aws/service/datasync"
	_ "github.com/hashicorp/terraform-provider-aws/service/dax"
	_ "github.com/hashicorp/terraform-provider-aws/service/directconnect"
	_ "github.com/hashicorp/terraform-provider-aws/service/dlm"
	_ "github.com/hashicorp/terraform-provider-aws/service/dms"
	_ "github.com/hashicorp/terraform-provider-aws/service/ds"
	_ "github.com/hashicorp/terraform-provider-aws/service/dynamodb"
	_ "github.com/hashicorp/terraform-provider-aws/service/ec2"
	_ "github.com/hashicorp/terraform-provider-aws/service/ecr"
	_ "github.com/hashicorp/terraform-provider-aws/service/ecrpublic"
	_ "github.com/hashicorp/terraform-provider-aws/service/ecs"
	_ "github.com/hashicorp/terraform-provider-aws/service/efs"
	_ "github.com/hashicorp/terraform-provider-aws/service/eks"
	_ "github.com/hashicorp/terraform-provider-aws/service/elasticache"
	_ "github.com/hashicorp/terraform-provider-aws/service/elasticbeanstalk"
	_ "github.com/hashicorp/terraform-provider-aws/service/elasticsearch"
	_ "github.com/hashicorp/terraform-provider-aws/service/elb"
	_ "github.com/hashicorp/terraform-provider-aws/service/elbv2"
	_ "github.com/hashicorp/terraform-provider-aws/service/emr"
	_ "github.com/hashicorp/terraform-provider-aws/service/events"
	_ "github.com/hashicorp/terraform-provider-aws/service/firehose"
	_ "github.com/hashicorp/terraform-provider-aws/service/fsx"
	_ "github.com/hashicorp/terraform-provider-aws/service/gamelift"
	_ "github.com/hashicorp/terraform-provider-aws/service/glacier"
	_ "github.com/hashicorp/terraform-provider-aws/service/globalaccelerator"
	_ "github.com/hashicorp/terraform-provider-aws/service/glue"
	_ "github.com/hashicorp/terraform-provider-aws/service/guardduty"
	_ "github.com/hashicorp/terraform-provider-aws/service/iam"
	_ "github.com/hashicorp/terraform-provider-aws/service/imagebuilder"
	_ "github.com/hashicorp/terraform-provider-aws/service/iot"
	_ "github.com/hashicorp/terraform-provider-aws/service/kafka"
	_ "github.com/hashicorp/terraform-provider-aws/service/kafkaconnect"
	_ "github.com/hashicorp/terraform-provider-aws/service/keyspaces"
	_ "github.com/hashicorp/terraform-provider-aws/service/kinesis"
	_ "github.com/hashicorp/terraform-provider-aws/service/kinesisanalytics"
	_ "github.com/hashicorp/terraform-provider-aws/service/kinesisanalyticsv2"
	_ "github.com/hashicorp/terraform-provider-aws/service/kms"
	_ "github.com/hashicorp/terraform-provider-aws/service/lambda"
	_ "github.com/hashicorp/terraform-provider-aws/service/lexmodels"
	_ "github.com/hashicorp/terraform-provider-aws/service/licensemanager"
	_ "github.com/hashicorp/terraform-provider-aws/service/lightsail"
	_ "github.com/hashicorp/terraform-provider-aws/service/memorydb"
	_ "github.com/hashicorp/terraform-provider-aws/service/mq"
	_ "github.com/hashicorp/terraform-provider-aws/service/mwaa"
	_ "github.com/hashicorp/terraform-provider-aws/service/neptune"
	_ "github.com/hashicorp/terraform-provider-aws/service/networkfirewall"
	_ "github.com/hashicorp/terraform-provider-aws/service/networkmanager"
	_ "github.com/hashicorp/terraform-provider-aws/service/opsworks"
	_ "github.com/hashicorp/terraform-provider-aws/service/pinpoint"
	_ "github.com/hashicorp/terraform-provider-aws/service/qldb"
	_ "github.com/hashicorp/terraform-provider-aws/service/quicksight"
	_ "github.com/hashicorp/terraform-provider-aws/service/rds"
	_ "github.com/hashicorp/terraform-provider-aws/service/redshift"
	_ "github.com/hashicorp/terraform-provider-aws/service/route53"
	_ "github.com/hashicorp/terraform-provider-aws/service/route53recoverycontrolconfig"
	_ "github.com/hashicorp/terraform-provider-aws/service/route53resolver"
	_ "github.com/hashicorp/terraform-provider-aws/service/s3"
	_ "github.com/hashicorp/terraform-provider-aws/service/s3control"
	_ "github.com/hashicorp/terraform-provider-aws/service/sagemaker"
	_ "github.com/hashicorp/terraform-provider-aws/service/schemas"
	_ "github.com/hashicorp/terraform-provider-aws/service/secretsmanager"
	_ "github.com/hashicorp/terraform-provider-aws/service/servicecatalog"
	_ "github.com/hashicorp/terraform-provider-aws/service/servicediscovery"
	_ "github.com/hashicorp/terraform-provider-aws/service/ses"
	_ "github.com/hashicorp/terraform-provider-aws/service/sns"
	_ "github.com/hashicorp/terraform-provider-aws/service/sqs"
	_ "github.com/hashicorp/terraform-provider-aws/service/ssm"
	_ "github.com/hashicorp/terraform-provider-aws/service/ssoadmin"
	_ "github.com/hashicorp/terraform-provider-aws/service/storagegateway"
	_ "github.com/hashicorp/terraform-provider-aws/service/synthetics"
	_ "github.com/hashicorp/terraform-provider-aws/service/timestreamwrite"
	_ "github.com/hashicorp/terraform-provider-aws/service/transfer"
	_ "github.com/hashicorp/terraform-provider-aws/service/waf"
	_ "github.com/hashicorp/terraform-provider-aws/service/wafregional"
	_ "github.com/hashicorp/terraform-provider-aws/service/wafv2"
	_ "github.com/hashicorp/terraform-provider-aws/service/workspaces"
	"github.com/hashicorp/terraform-provider-aws/sweep"
)

func TestMain(m *testing.M) {
	sweep.SweeperClients = make(map[string]interface{})
	resource.TestMain(m)
}
